// <auto-generated />
using System;
using ContactNotePad.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactNotePad.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526184524_UserContactRelation")]
    partial class UserContactRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ContactNotePad.Models.Contact", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<uint>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Address = "123 Main St",
                            Description = "Test contact John",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890",
                            UserId = 1u,
                            created_at = new DateTime(2025, 5, 26, 18, 45, 23, 661, DateTimeKind.Utc).AddTicks(9785)
                        },
                        new
                        {
                            Id = 2u,
                            Address = "456 Oak Ave",
                            Description = "Test contact Jane",
                            Email = "jane.doe@example.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            PhoneNumber = "987-654-3210",
                            UserId = 1u,
                            created_at = new DateTime(2025, 5, 26, 18, 45, 23, 662, DateTimeKind.Utc).AddTicks(1558)
                        });
                });

            modelBuilder.Entity("ContactNotePad.Models.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Email = "admin@gmail.com",
                            Nickname = "admin",
                            PasswordHash = "admin"
                        },
                        new
                        {
                            Id = 2u,
                            Email = "user@gmail.com",
                            Nickname = "user",
                            PasswordHash = "user"
                        });
                });

            modelBuilder.Entity("ContactNotePad.Models.Contact", b =>
                {
                    b.HasOne("ContactNotePad.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContactNotePad.Models.User", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
